language: java
services:
  - mysql
  - postgresql
before_install:
  - mvn -v
  - git pull --unshallow
before_script:
  - mysql -e 'create database uaa;'
  - psql -c 'create database uaa;' -U postgres
  - psql -c "create user root with superuser password 'changeme';" --dbname=uaa -U postgres
  - mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('changeme');" 
  - mysql -e "SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('changeme');"  
install: 
  -  mvn -U clean --quiet -DskipTests=true
  -  mvn -U install --quiet -DskipTests=true
script: 
  - mvn test --quiet -Dspring.profiles.active=default,mysql
  - mvn test --quiet -Dspring.profiles.active=default,postgresql
  - ./.run-script.sh
  - mvn verify --quiet
  - kill -9 `cat mvn.pid`
  - rm -f mvn.pid
  - ./.run-script.sh "-Dspring.profiles.active=default,mysql"
  - mvn verify --quiet
  - kill -9 `cat mvn.pid`
  - rm -f mvn.pid
  - ./.run-script.sh  "-Dspring.profiles.active=default,postgresql" 
  - mvn verify --quiet
  - kill -9 `cat mvn.pid`
  - rm -f mvn.pid
  